### ISSUE TITLE
Worker failed to boot

### ISSUE THREAD

**Issue by jundymek** [daftcode/python_levelup_2018#12]
Powoli zaczynam się poddawać. Od dwóch dni męczę się z połączeniem aplikacji z bazą danych na heroku i niestety moje próby są wyłącznie pasmem porażek. Poniżej wrzucam logi z serwera heroku. Może komuś uda się naprowadzić mnie na właściwe tory:

`
2018-04-09T21:44:21.094537+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
2018-04-09T21:44:21.094674+00:00 app[web.1]:     self.reap_workers()
2018-04-09T21:44:21.094677+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
2018-04-09T21:44:21.094886+00:00 app[web.1]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2018-04-09T21:44:21.094923+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2018-04-09T21:44:21.094925+00:00 app[web.1]:
2018-04-09T21:44:21.094926+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2018-04-09T21:44:21.094927+00:00 app[web.1]:
2018-04-09T21:44:21.094928+00:00 app[web.1]: Traceback (most recent call last):
2018-04-09T21:44:21.094931+00:00 app[web.1]:   File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
2018-04-09T21:44:21.095021+00:00 app[web.1]:     sys.exit(run())
2018-04-09T21:44:21.095024+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
2018-04-09T21:44:21.095132+00:00 app[web.1]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2018-04-09T21:44:21.095135+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 203, in run
2018-04-09T21:44:21.095359+00:00 app[web.1]:     super(Application, self).run()
2018-04-09T21:44:21.095363+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
2018-04-09T21:44:21.095464+00:00 app[web.1]:     Arbiter(self).run()
2018-04-09T21:44:21.095467+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 231, in run
2018-04-09T21:44:21.095600+00:00 app[web.1]:     self.halt(reason=inst.reason, exit_status=inst.exit_status)
2018-04-09T21:44:21.095601+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 344, in halt
2018-04-09T21:44:21.095770+00:00 app[web.1]:     self.stop()
2018-04-09T21:44:21.095772+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
2018-04-09T21:44:21.095947+00:00 app[web.1]:     time.sleep(0.1)
2018-04-09T21:44:21.095948+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
2018-04-09T21:44:21.096078+00:00 app[web.1]:     self.reap_workers()
2018-04-09T21:44:21.096081+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
2018-04-09T21:44:21.096288+00:00 app[web.1]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2018-04-09T21:44:21.096292+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2018-04-09T21:46:28.789297+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/cities" host=alhemysql.herokuapp.com request_id=65262c28-cc63-4b8f-a625-7236167288bd fwd="89.70.133.74" dyno= connect= service= status=503 bytes= protocol=https
2018-04-09T21:49:46.193489+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/cities" host=alhemysql.herokuapp.com request_id=e5e8c1e8-42a7-45d4-a1bb-46f2b7dc1418 fwd="89.70.133.74" dyno= connect= service= status=503 bytes= protocol=https
2018-04-09T21:57:43.885495+00:00 heroku[web.1]: State changed from crashed to starting
2018-04-09T21:57:47.418652+00:00 heroku[web.1]: Starting process with command `gunicorn app:app`
2018-04-09T21:57:49.017894+00:00 app[web.1]: [2018-04-09 21:57:49 +0000] [4] [INFO] Starting gunicorn 19.7.1
2018-04-09T21:57:49.018394+00:00 app[web.1]: [2018-04-09 21:57:49 +0000] [4] [INFO] Listening at: http://0.0.0.0:55377 (4)
2018-04-09T21:57:49.018492+00:00 app[web.1]: [2018-04-09 21:57:49 +0000] [4] [INFO] Using worker: sync
2018-04-09T21:57:49.021914+00:00 app[web.1]: [2018-04-09 21:57:49 +0000] [8] [INFO] Booting worker with pid: 8
2018-04-09T21:57:49.040345+00:00 app[web.1]: [2018-04-09 21:57:49 +0000] [9] [INFO] Booting worker with pid: 9
2018-04-09T21:57:49.051977+00:00 app[web.1]: /app/.heroku/python/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
2018-04-09T21:57:49.051980+00:00 app[web.1]:   """)
2018-04-09T21:57:49.060981+00:00 app[web.1]: /app/.heroku/python/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
2018-04-09T21:57:49.060984+00:00 app[web.1]:   """)
2018-04-09T21:57:49.559303+00:00 heroku[web.1]: State changed from starting to up
2018-04-09T21:57:50.232313+00:00 heroku[web.1]: Process exited with status 3
2018-04-09T21:57:50.243017+00:00 heroku[web.1]: State changed from up to crashed
2018-04-09T21:57:50.001511+00:00 app[web.1]: /app/.heroku/python/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
2018-04-09T21:57:50.001574+00:00 app[web.1]:   'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
2018-04-09T21:57:50.005761+00:00 app[web.1]: [2018-04-09 21:57:50 +0000] [8] [ERROR] Exception in worker process
2018-04-09T21:57:50.005766+00:00 app[web.1]:     worker.init_process()
2018-04-09T21:57:50.005763+00:00 app[web.1]: Traceback (most recent call last):
2018-04-09T21:57:50.005765+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2018-04-09T21:57:50.005767+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2018-04-09T21:57:50.005768+00:00 app[web.1]:     self.load_wsgi()
2018-04-09T21:57:50.005770+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-04-09T21:57:50.005769+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2018-04-09T21:57:50.005772+00:00 app[web.1]:     self.callable = self.load()
2018-04-09T21:57:50.005773+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-04-09T21:57:50.005771+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-04-09T21:57:50.005774+00:00 app[web.1]:     return self.load_wsgiapp()
2018-04-09T21:57:50.005775+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-04-09T21:57:50.005776+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-04-09T21:57:50.005777+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2018-04-09T21:57:50.005778+00:00 app[web.1]:     __import__(module)
2018-04-09T21:57:50.005781+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 424, in create_engine
2018-04-09T21:57:50.005779+00:00 app[web.1]:   File "/app/app.py", line 31, in <module>
2018-04-09T21:57:50.005780+00:00 app[web.1]:     engine = create_engine(conn)
2018-04-09T21:57:50.005782+00:00 app[web.1]:     return strategy.create(*args, **kwargs)
2018-04-09T21:57:50.005783+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 52, in create
2018-04-09T21:57:50.005784+00:00 app[web.1]:     plugins = u._instantiate_plugins(kwargs)
2018-04-09T21:57:50.009380+00:00 app[web.1]: /app/.heroku/python/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
2018-04-09T21:57:50.005788+00:00 app[web.1]: AttributeError: 'psycopg2.extensions.connection' object has no attribute '_instantiate_plugins'
2018-04-09T21:57:50.006134+00:00 app[web.1]: [2018-04-09 21:57:50 +0000] [8] [INFO] Worker exiting (pid: 8)
2018-04-09T21:57:50.009397+00:00 app[web.1]:   'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
2018-04-09T21:57:50.013604+00:00 app[web.1]: Traceback (most recent call last):
2018-04-09T21:57:50.013602+00:00 app[web.1]: [2018-04-09 21:57:50 +0000] [9] [ERROR] Exception in worker process
2018-04-09T21:57:50.013606+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2018-04-09T21:57:50.013607+00:00 app[web.1]:     worker.init_process()
2018-04-09T21:57:50.013608+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2018-04-09T21:57:50.013609+00:00 app[web.1]:     self.load_wsgi()
2018-04-09T21:57:50.013610+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2018-04-09T21:57:50.013615+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-04-09T21:57:50.013611+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-04-09T21:57:50.013616+00:00 app[web.1]:     return self.load_wsgiapp()
2018-04-09T21:57:50.013613+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-04-09T21:57:50.013614+00:00 app[web.1]:     self.callable = self.load()
2018-04-09T21:57:50.013617+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-04-09T21:57:50.013619+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2018-04-09T21:57:50.013620+00:00 app[web.1]:     __import__(module)
2018-04-09T21:57:50.013618+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-04-09T21:57:50.013622+00:00 app[web.1]:     engine = create_engine(conn)
2018-04-09T21:57:50.013621+00:00 app[web.1]:   File "/app/app.py", line 31, in <module>
2018-04-09T21:57:50.013624+00:00 app[web.1]:     return strategy.create(*args, **kwargs)
2018-04-09T21:57:50.013623+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 424, in create_engine
2018-04-09T21:57:50.013625+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 52, in create
2018-04-09T21:57:50.013626+00:00 app[web.1]:     plugins = u._instantiate_plugins(kwargs)
2018-04-09T21:57:50.014005+00:00 app[web.1]: [2018-04-09 21:57:50 +0000] [9] [INFO] Worker exiting (pid: 9)
2018-04-09T21:57:50.013629+00:00 app[web.1]: AttributeError: 'psycopg2.extensions.connection' object has no attribute '_instantiate_plugins'
2018-04-09T21:57:50.174093+00:00 app[web.1]: [2018-04-09 21:57:50 +0000] [4] [INFO] Reason: Worker failed to boot.
2018-04-09T21:57:50.173979+00:00 app[web.1]: [2018-04-09 21:57:50 +0000] [4] [INFO] Shutting down: Master
2018-04-09T22:01:36.680551+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=alhemysql.herokuapp.com request_id=0ea59cfb-71f2-49b4-bff0-512ce1e9deca fwd="89.70.133.74" dyno= connect= service= status=503 bytes= protocol=https
2018-04-09T22:01:39.802282+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/cities" host=alhemysql.herokuapp.com request_id=91ccada8-354a-421b-8ea6-ac3265d9b8a6 fwd="89.70.133.74" dyno= connect= service= status=503 bytes= protocol=https
`

**Comment by halicki** [comment]
@jundymek 
W twoich logach widać, że gunicorn wielokrotnie próbuje odpalić aplikację, niestety z powodu powtarzającego się błędu (`AttributeError: 'psycopg2.extensions.connection' object has no attribute '_instantiate_plugins`) nie jest w stanie tego zrobić.
Wrzuć swój kod na githuba. Spróbujemy zdebugować go tam.

**Comment by jundymek** [comment]
Udało mi się uporać z tym problemem we własnym zakresie. Źle łączyłem się z bazą i to powodowało jakieś problemy. Kodu nie wrzucam bo z tego wszystkiego nie mam pojęcia, która wersja moich wypocin generowała te błędy. W końcu się udało połączyć, to teraz mogę się uczyć SQLAlchemy i próbować rozwiązać zadanie...;)
